version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: express_db # Change this to the actual application database name
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db  

  express-app:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: express_app # Change this to the actual application name
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mongo
      DB_USER: root
      DB_PASSWORD: example
      DB_PORT: 27017
      NODE_ENV: development
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app 

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password

volumes:
  mongo_data:  